Modif2

diff --git a/Library-management/Jenkinsfile b/Library-management/Jenkinsfile
--- a/Library-management/Jenkinsfile
+++ b/Library-management/Jenkinsfile
@@ -93,8 +93,7 @@ pipeline {
                     docker run -d --name test-backend --network app-network -p 9091:9090 ${IMAGE_NAME_BACK}:${IMAGE_TAG}
                     docker run -d --name test-frontend --network app-network -p 80:80 ${IMAGE_NAME_FRONT}:${IMAGE_TAG}
 
-                    echo "Waiting 10 seconds for containers to start..."
-                    timeout /t 10 >nul
+
 
                     echo "Containers status:"
                     docker ps
@@ -103,21 +102,13 @@ pipeline {
                     // Health checks
                     bat """
                     echo "Testing containers health..."
-                    curl -f http://localhost:9091/actuator/health || (echo "❌ Backend failed!" & exit /b 1)
+                    curl -f http://localhost:9091/|| (echo "❌ Backend failed!" & exit /b 1)
                     curl -f http://localhost:80/ || (echo "❌ Frontend failed!" & exit /b 1)
                     echo "✅ Containers are running and reachable!"
                     """
                 }
             }
-            post {
-                always {
-                    bat """
-                    echo "🧹 Cleaning up test containers..."
-                    docker rm -f test-backend || echo "Already removed"
-                    docker rm -f test-frontend || echo "Already removed"
-                    """
-                }
-            }
+
         }
     }
 
